//Ces constantes permettent l'utilisation de certains caractères comme "ç,é,è ..." dans SDL_TTF

#define agrave "\xe0"
#define aacute "\xe1"
#define acirc  "\xe2"
#define auml   "\xe4"
#define ccedil "\xe7"
#define egrave "\xe8"
#define eacute "\xe9"
#define ecirc  "\xea"
#define euml   "\xeb"
#define icirc  "\xee"
#define iuml   "\xef"
#define ocirc  "\xf4"
#define ugrave "\xf9"
#define ucirc  "\xfb"
#define uuml   "\xfc"
#define Ccedil "\xc7"
#define Egrave "\xc8"
#define Eacute "\xc9"
#define Ecirc  "\xca"
